README.md

Fixes typo in Readme

---

CHANGELOG.md

Update changelog to include released bugfix

---

CHANGELOG.md

Favorite graph update

---

preview-docs/PreRequestScripts.md

Please [see md file](https://github.com/apollographql/apollo-studio-community/blob/e1493c024db2e4c00cffd188abb61cb375bce87c/preview-docs/PreRequestScripts.md)

Preview doc for environment variables and pre-request scripts

---

CHANGELOG.md

[preview markdown file](https://github.com/apollographql/apollo-studio-community/blob/7065effd0bbb9acce81176e603799ddff2af3ed9/CHANGELOG.md)

changelog - auto linking in comments for TypeName.fieldName

---

preview-docs/Webhooks.md

This is the first draft of some sample docs for our new Webhooks feature (and my first PR at Apollo!). Please give me your feedback! More details to follow as we finish the design.

Add Webhooks, draft 1

---

CHANGELOG.md

Update CHANGELOG with faster graph list load

---

CHANGELOG.md

Changed the photo to reflect the new changes to this pane in Explorer

Update changelog entry for default headers

---

CHANGELOG.md

We have released [Sandbox](https://studio.apollographql.com/sandbox), making the Apollo Explorer openly available to any developer, with no login required.
Full details on the release in our announcement post: [Apollo Sandbox: an open GraphQL IDE for local development
](https://www.apollographql.com/blog/announcement/platform/apollo-sandbox-an-open-graphql-ide-for-local-development/).
[![image](https://user-images.githubusercontent.com/743976/122124968-fe315d00-cdfd-11eb-91df-910408dc8d9c.png)](https://www.apollographql.com/blog/announcement/platform/apollo-sandbox-an-open-graphql-ide-for-local-development/)

Update CHANGELOG.md for sandbox

---

CHANGELOG.md

Add entry for the new org picker

Changelog: Org Picker

---

CHANGELOG.md

https://github.com/apollographql/apollo-studio-community/blob/3a1ea5ed6e4fc3025a19652b986698c2fd68f9bc/CHANGELOG.md

Changelog: add check status filters

---

CHANGELOG.md

https://github.com/apollographql/apollo-studio-community/blob/87294f99cfdc4f7aceb98fc52df64068b9a55b2e/CHANGELOG.md

Changelog: composition details in checks

---

CHANGELOG.md

Add changelog for Query Plan Previews for registered Fed2 graphs in Apollo Studio Explorer

Query Plan Previews for registered Fed2 graphs in Apollo Studio Explorer

---

CHANGELOG.md

changelog for operation collections

---

CHANGELOG.md

Reverts apollographql/apollo-studio-community#180

Revert "Subgraph fetch trace rendering improvements"

---

CHANGELOG.md

Manually fetch schema when auto-polling is turned off!

manually fetch schema when auto-polling is turned off

---

CHANGELOG.md

Adds the GraphOS Platform API to the Studio changelog. Please hold on merge until we've published the blog post.

Platform API announcement

---

CHANGELOG.md

This PR updates the changelog for improvements to contract variant parity in Studio. Specifically, this PR adds entries for query plan previews and subgraph information.

Update CHANGELOG.md for contract variant parity improvements

---

CHANGELOG.md

Update changelog for show entities

---

CHANGELOG.md

Disable operation checks

---

CHANGELOG.md

Adds info about the PQ release that happened on 8/10. (LMK if backdating isn't ok, and I'll change to today :) )

Update CHANGELOG.md with persisted queries

---

CHANGELOG.md

Fix broken image

---

CHANGELOG.md

Add visualization changelog

---

CHANGELOG.md

Changelog entry for proposal webhook notifications

Changelog entry for proposal webhook notifications

---

CHANGELOG.md

New Operation Checks UI Enhancements

---

CHANGELOG.md

add log for variant level proposal check config

add log for variant level proposal check config

---

CHANGELOG.md

https://apollographql.atlassian.net/browse/PROPOSALS-240

Update CHANGELOG.md for proposals editor improvements

---

CHANGELOG.md

Orbit light theme changelog

---

CHANGELOG.md

changelog entry for schema proposal checks behaviour change for descriptions. To be merged after flag flipped.

Update CHANGELOG.md for schema proposal checks WARN instead of ERROR on missing proposals
